[config]
schemaVersion = "0.0.1"

[package]
namespace = "Gobs"
name = "Peglin Relic Library"
versionNumber = "2.0.1"
description = "A Library for creating Relics in Peglin"
websiteUrl = "https://github.com/crazyjackel/Peglin-Relic-Lib"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Peglin = "5.4.1901"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./dist"
target = ""

[[build.copy]]
source = "Include"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["peglin"]
categories = []
